title: "Robotics Scientist"
description: "Autonomous Systems & AI Research"
theme: minima   # theme đẹp, dễ tùy chỉnh

markdown: kramdown

# Navigation links
nav:
  - title: "Giới thiệu"
    url: /about
  - title: "Hướng nghiên cứu"
    url: /research
  - title: "Dự án"
    url: /projects
  - title: "Công bố khoa học"
    url: /pubs
  - title: "Giảng dạy"
    url: /teaching
  - title: "Liên hệ"
    url: /contact
